### ISSUE TITLE
doesn't work anymore

### ISSUE THREAD

**Issue by bruno-1337** [amWilq/Yupoo-PhotoDownloader#2]
i already tried to reinstall python and all packages but still can't figure out why it doesn't work (doesnt save any photo)
![Screenshot_3](https://user-images.githubusercontent.com/71904759/146055102-123fa0b3-7942-460a-b2df-4521b3358d51.jpg)

**Comment by amWilq** [comment]
Hi!
fixed, changed 28 line, You can clone repo again. Let me know if it's working now.

**Comment by bruno-1337** [comment]
![image](https://user-images.githubusercontent.com/71904759/146277032-80d63b6a-30fe-40c5-98ee-156476b8e119.png)
still doesn't work

**Comment by amWilq** [comment]
"pip install lxml" in Console.

**Comment by bruno-1337** [comment]
yeah thats what i was going to post here xd
